### PR TITLE
Tune logging: "Using hardcoded default" as info

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by rsprinkle** [comment]
I think that this is definitely a warning.  It should be rare that no configuration is provided so when it isn't it is probably an indication of a problem.

**Comment by tvand** [comment]
> I think that this is definitely a warning. It should be rare that no configuration is provided so when it isn't it is probably an indication of a problem.

+1 I think we should leave it as a warning.

**Comment by simon04** [comment]
The problem is that this warning is unavoidable when using `CompositeCacheManager.getUnconfiguredInstance()`:

```
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.configure(ThreadPoolManager.java:324)
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.<init>(ThreadPoolManager.java:96)
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.getInstance(ThreadPoolManager.java:202)
	at org.apache.commons.jcs.engine.control.event.ElementEventQueue.<init>(ElementEventQueue.java:56)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.initialize(CompositeCacheManager.java:276)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.getUnconfiguredInstance(CompositeCacheManager.java:214)
```

**Comment by tvand** [comment]
Could I have the complete stack trace please?

**Comment by simon04** [comment]
Basically, this is all. I set a breakpoint at the `log.warn("No configuration settings found…` line and executed `new RuntimeException().printStackTrace()` There's the full stack trace from running @JOSM:

```
java.lang.RuntimeException
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.configure(ThreadPoolManager.java:324)
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.<init>(ThreadPoolManager.java:96)
	at org.apache.commons.jcs.utils.threadpool.ThreadPoolManager.getInstance(ThreadPoolManager.java:202)
	at org.apache.commons.jcs.engine.control.event.ElementEventQueue.<init>(ElementEventQueue.java:56)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.initialize(CompositeCacheManager.java:276)
	at org.apache.commons.jcs.engine.control.CompositeCacheManager.getUnconfiguredInstance(CompositeCacheManager.java:214)
	at org.openstreetmap.josm.data.cache.JCSCacheManager.initialize(JCSCacheManager.java:156)
	at org.openstreetmap.josm.data.cache.JCSCacheManager.getCache(JCSCacheManager.java:191)
	at org.openstreetmap.josm.gui.layer.AbstractCachedTileSourceLayer.getCache(AbstractCachedTileSourceLayer.java:118)
	at org.openstreetmap.josm.gui.layer.TMSLayer.getCache(TMSLayer.java:144)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by simon04** [comment]
Addressed in https://github.com/apache/commons-jcs/commit/b9fb77b351690414335d9bb8864b7f21e13e7a23

**Pull request closed without merging**
