### PR TITLE
JCS-216 - Redundant cast call

### PR DESCRIPTION
**Pull request by arturobernalg**
Replace class.cast whit explicit Cast

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hi,
the rational to use .class.cast instead of (<type>) is it enables to use a function (so is consistent with other programming style) but also to debug it properly at need "directly" whereas with a standard cast it is hardcoder to do.
So overall I think we should keep it if possible.

**Comment by arturobernalg** [comment]
HI @arturobernalg 
I don't  really understand about "enables to use a function". I think the use does't change.
TY

**Comment by rmannibucau** [comment]
@arturobernalg .class.cast is a function in java.lang.Class class, as any java method which is the reason it was preferred for this part of the code over instanceof/() casting which is a language feature directly translated to a bytecode instruction.

**Comment by arturobernalg** [comment]
> @arturobernalg .class.cast is a function in java.lang.Class class, as any java method which is the reason it was preferred for this part of the code over instanceof/() casting which is a language feature directly translated to a bytecode instruction.

Hi @rmannibucau 
suena razonable

**Pull request closed without merging**
