### PR TITLE
Tune logging: assume that info is enabled

### PR DESCRIPTION
**Pull request by simon04**
This removes lots of clutter in the code.

### CODE REVIEW

**Comment by rdsprinkle** [comment]
Bypassing the tests for log.info enabled means that each item always performs a String concatenation to build the log message.  You should pass the message in as separate arguments and then log will only perform the concatenation if it is enabled.

**Comment by simon04** [comment]
I'm happy to revise my PR if there's a realistic change for its approval. What about my other, less disputable PRs #8 and #9?

**Comment by rsprinkle** [comment]
> 
> 
> I'm happy to revise my PR if there's a realistic change for its approval. What about my other, less disputable PRs #8 and #9?

I am just a user, so I don't have any input into the approval.  But given the low overhead of a call to a disabled log statement and the reduction in clutter, I personally would be in favor, provided the cost of building the log message was eliminated when not used.  Hence my earlier comment.

**Comment by simon04** [comment]
@tvand, you've convinced me …

**Pull request closed without merging**
